allowBuilds:
    '@parcel/watcher': true
    esbuild: true
    sharp: true

minimumReleaseAgeExclude:
    - '@silesiansolutions/search-quality-kit'

onlyBuiltDependencies:
    - '@parcel/watcher'
    - esbuild
    - sharp
